ALTER TABLE bookings ALTER COLUMN checkin_date TYPE TIMESTAMPTZ;
ALTER TABLE bookings ALTER COLUMN checkout_date TYPE TIMESTAMPTZ;

ALTER TABLE room_holds ALTER COLUMN checkin_date TYPE TIMESTAMPTZ;
ALTER TABLE room_holds ALTER COLUMN checkout_date TYPE TIMESTAMPTZ;
